pages/downloads.vue

Not super picky, but this was an easy way to get the same formatting (with commas).

Downloads: Use date format from blog

---

components/disclaimer.vue

Fixes #10. Pending wrapping from @btkostner.

Disclaimer: Link to GitHub release project

---

server/auth-callback.js

I did not test, but I'm assuming this might be the fix to #15

Lower case username checks

---

data/allowlist.json

Please sir, can I have some ISOs?

Allowlist: add David

---

server/auth-url.js

Fixes #24 
https://developer.github.com/apps/building-oauth-apps/understanding-scopes-for-oauth-apps/#available-scopes

update oauth scope to only read user info

---

components/disclaimer.vue

As mentioned by @davidmhewitt in Slack.

Disclaimer: Mention GNOME session issue

---

server/auth-url.js

Revert "update oauth scope to only read user info"

---

data/development-images.json
pages/downloads.vue
server/images.js
store/images.js

Add Pinebook Pro images

---

data/allowlist.json
server/auth-callback.js
server/auth-url.js

Allows anyone in the "elementary" organization to login

allow login for people in elementary org

---

pages/downloads.vue

Fixes https://github.com/elementary/builds/issues/22

UTC timezone the outputted date

---

data/allowlist.json

Add Lukasz to allowlist

---

data/allowlist.json5
package.json
server/auth-callback.js

Fixes https://github.com/elementary/builds/issues/23
The list changes are just for example

add json5 for allowlist comments

---

components/layout-navbar.vue
store/auth.js

Add logout button in subnav

---

server/auth-url.js

PR for issue fixes #24
Verified working for me locally

change scope to only read user

---

assets/styles/layout.scss
pages/downloads.vue

Add checksum link for old builds

---

package-lock.json

This is a lot of upgrades and I'm not sure if it will break actual deployments or not, depends on the node version.
```
lewis@658BL13-ele:~/Source/GitHub/builds$ node -v
v14.15.5
lewis@658BL13-ele:~/Source/GitHub/builds$ npm -v
6.14.11
```

npm update && npm audit fix

---

components/disclaimer.vue

Disclaimer: add note about upgrading

---

server/beta.js

fixes the ws url for magnet downloads

Update magnet link

---

pages/beta.vue
pages/index.vue
server/beta.js

Need to double-check copy and blog URLs

Release OS 6 Beta 2

---

data/development-images.json
store/images.js

Add support for 6.1 builds

---

components/layout-navbar.vue

Navbar: Remove StackExchange link

---

store/images.js

Update images.js for 7.1

---

server/auth-callback.js

I think the $10 early access limit is just too high. I think the value proposition here is more appropriate to be just any sponsor. I'd like to encourage a lot more signups here

auth-callback: Allow any sponsor

---

package-lock.json
package.json

Tested that JWT login tokens still work

Bump jsonwebtoken

---

.github/dependabot.yml

Not sure if this update spec isn't a bit aggressive but it might help it not get so outdated.

Add automatic updates with dependabot

---

package-lock.json
package.json

Tested that the GitHub API calls we use this for still work through the major version bumps

Bump graphql-request

---

components/layout-navbar.vue
package-lock.json
package.json

Updates the npm dependencies and removes the Twitter/Facebook links while we're here.

Update fontawesome icons

---

package-lock.json
package.json

Revert "Bump graphql-request from 6.1.0 to 7.0.1"

---

components/layout-navbar.vue

Based on the recommendation at https://fontawesome.com/v4/accessibility/

Navbar: make social icons screen reader accessible

---

components/layout-navbar.vue

I don't know how vue works :upside_down_face: Added missing import

Navbar: fix discord icon

---

pages/downloads.vue

Fixes the part 2. of https://github.com/elementary/builds/issues/267#issuecomment-3023742352
- ~~Haven't tested yet~~ Not sure how to test this in a non-production environment
- I have never experienced Vue.js

Support downloading arm64 Daily images
